name: Test Notebooks

on:
  push:
    paths:
      - '**.ipynb'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install nbconvert nbformat

    - name: Execute changed notebooks
      run: |
        git diff --name-only HEAD^ HEAD | grep '\.ipynb$' | while read -r file; do
          jupyter nbconvert --to notebook --execute --inplace "$file"
        done

    - name: Check for errors
      run: |
        for file in $(find . -type f -name "*.html"); do
          if grep -q "Execution failed" "$file"; then
            echo "Notebook execution failed: $file"
            exit 1
          fi
        done
